### ISSUE TITLE
github icon link broken

### ISSUE THREAD

**Issue by seemajune** [learn-co-curriculum/angular-project-setup-lab#2]
when i click on the octocat icon from learn.co, it goes to: https://github.com/learn-co-students/angular-project-setup-lab-Continued%20Education

should go to:
https://github.com/learn-co-students/angular-project-setup-lab-Continued-Education

**Comment by deniznida** [comment]
@joshrowley was this fixed? because when I click on the octocat I'm redirected to the right repo/link

**Comment by joshrowley** [comment]
Yeah, that should be fixed now, thanks for following up @deniznida
