### ISSUE TITLE
Instructions for installing the latest version of Angular missing

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/angular-project-setup-lab#5]
The first objective reads:

`Download the latest version of Angular 1.x`

But no instructions are provided. Also at the end of the lesson, students are asked to visit `index.html` without instructions on how to start the app:

``````
Next, we need to tell Angular about our controller. Add this to the bottom of MainController.js:

angular
  .module('app')
  .controller('MainController', MainController);
HELLO, YOUR NAME!

Now open up index.html in Google Chrome and you should see Hello, your name! Wow - our first small Angular application. ```
``````

**Comment by onyoo** [comment]
Run: `sudo npm install`
Server: `python -m SimpleHTTPServer 8000`

**Comment by ipc103** [comment]
thanks for raising this issue @onyoo - we've just updated the instructions for this lab!
